{{- range $service := .Values.gateway.services }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: api
spec:
  hosts:
    - '*'
  gateways:
    - istio-system/main-gateway
  http:
    {{- range $route, $val := $service.routes }}
    - match:
      - uri:
          prefix: "/{{ $service.name }}/{{ $route.path }}"
      rewrite:
        uri: "/"
      route:
        - destination:
            port:
              number: {{ .Values.service.port }}
            host: "{{ .Values.name }}.api.svc.cluster.local"
  {{- end }}
{{- end }}